name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            supermark
            tqdm
      - name: checkout
        uses: actions/checkout@v2
      - run: |
          ls
      - run: |
          pwd
          tree
      - run: |
          cd ..
          pwd
      - name: Install pandoc
        run: |
          $CONDA/bin/conda install pandoc
          ln -s $CONDA/bin/pandoc /usr/local/bin/pandoc
      - name: Run Supermark
         run: |
          supermark --all
      - name: push
        uses: actions-x/commit@v2
